services:
  database:
    build: .
    image: postgres:16-alpine
    ports:
      - 5434:5432
    env_file:
      - .env
    networks:
      - my-network
  migrate:
    build: .
    image: migration:v2
    links:
      - database
    networks:
      - my-network
networks:
  my-network:
    driver: bridge